[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "le-wm-minecraft"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "opencv-python",
    "matplotlib",
    "stable-worldmodel",
    "hydra-core",
    "pytest",
    "torch",
    "torchvision",
    "h5py",
    "pillow",
    "wandb",
    "imageio"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
