defaults:
  - _self_

config_name: ${hydra:job.name}

paths:
  data_dir: data
  checkpoint_dir: artifacts/checkpoints
  fixtures_dir: artifacts/fixtures
  logs_dir: artifacts/charts
  final_models_dir: artifacts/final_models
  evals_dir: artifacts/evals
  
  best_model: artifacts/checkpoints/best_model.pt
  latest_model: artifacts/checkpoints/latest_model.pt

  # goal frames
  nav_goal_frame: artifacts/fixtures/goal_tree_nav.pkl
  chop_goal_frame: artifacts/fixtures/goal_tree_chop.pkl

  # evals
  probe_data: data/probe_evals

checkpoint_path: ${paths.checkpoint_dir}
model_path: ${paths.latest_model}

wandb:
  project: lewm
  entity: null # defaults to wandb account

# == Shared ==
action_dim: 10
batch_size: 128
total_epochs: 5
warmup_epochs: 1
sub_trajectory: 8 # 8 frames and 8 actions

sigreg:
  num_proj: 1024
  factor: 1.0
  phi: 0.606 # frequency of normal dist. for epps pulley test
  lambd: 0.1

inverse_dynamics:
  lambd: 0.5

# == ViT encoder hyperparameters ==
vit:
  image_size: 64
  patch_size: 8 # LeWM paper uses 14; this project currently uses 8 for 64x64 frames.
  num_channels: 3
  num_patches: 64 # (64 / 8) x (64 / 8)

  embedding_dim: 192
  attention_heads: 3
  mlp_hidden_nodes: 768 #  192 x 4 (for scaling laws)
  transformer_blocks: 12

# == Predictor hyperparameters ==
predictor:
  transformer_blocks: 6
  attention_heads: 16
  dropout: 0.10
  history_len: 8 # causal mask sees past 8 timestamps

optimizer:
  lr: 5e-5
  weight_decay: 1e-3

# == Probe hyperparameters ==
probe:
  epochs: 10
  batch_size: 128

# == Planner hyperparameters ==
planner:
  max_iter: 10
  n_samples: 300
  n_elites: 30
  rollout_batch_size: 64
  planning_horizon: 8
  max_steps: 200
  success_threshold: 0.5 # success threshold for each goal
  success_distance: 4.0 # minecraft's block interaction threshold is 4.5 blocks
  chop_done_mse: 0.05 # latent MSE threshold to determine if chopping is complete
  chop_done_patience: 3 # consecutive low-MSE steps before CHOP is complete
  chop_max_steps: 15 # always advance after this many CHOP steps

# == Malmo env/task settings ==
env:
  configs:
    discrimination_test:
      xml: Malmo/py27/environments/discrimination_test.xml
      target_name: oak_tree
      target_position: [-6.0, 15.0]
    single_tree_navigation:
      xml: Malmo/py27/environments/single_tree_navigation.xml
      target_name: oak_tree
      target_position: [0.0, 15.0]
    single_raised_tree_navigation:
      xml: Malmo/py27/environments/single_raised_tree_navigation.xml
      target_name: oak_tree
      target_position: [0.0, 15.0]
    seed_world:
      xml: Malmo/py27/environments/single_raised_tree_navigation.xml
      target_name: oak_tree
      target_position: [173.0, 234.0]
    multi_tree_navigation:
      xml: Malmo/py27/environments/multi_tree_navigation.xml
      target_name: oak_tree
      target_position: [0.0, 15.0]
      target_positions:
        - [0.0, 15.0]
        - [-7.0, 12.0]
        - [6.0, 18.0]
        - [3.0, 25.0]
        - [-10.0, 23.0]